# Generated by Django 4.0.2 on 2022-02-23 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_spend_ar',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='time_spend_pdf',
            name='duration',
        ),
        migrations.AddField(
            model_name='time_spend_ar',
            name='beginn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time_spend_ar',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='time_spend_pdf',
            name='beginn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time_spend_pdf',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
