# Generated by Django 4.0.2 on 2022-02-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_time_spend_ar_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_spend_ar',
            name='beginn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='time_spend_pdf',
            name='beginn',
            field=models.DateTimeField(null=True),
        ),
    ]
