# Generated by Django 4.0.2 on 2022-02-24 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('my_app', '0003_alter_time_spend_ar_beginn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NASA_TLX_AR',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Mental_Demand_Rating', models.SmallIntegerField(null=True)),
                ('Physical_Demand_Rating', models.SmallIntegerField(null=True)),
                ('Temporal_Demand_Rating', models.SmallIntegerField(null=True)),
                ('Performance_Rating', models.SmallIntegerField(null=True)),
                ('Effort_Rating', models.SmallIntegerField(null=True)),
                ('Frustration_Rating', models.SmallIntegerField(null=True)),
                ('Mental_Demand_Tally', models.SmallIntegerField(null=True)),
                ('Physical_Demand_Tally', models.SmallIntegerField(null=True)),
                ('Temporal_Demand_Tally', models.SmallIntegerField(null=True)),
                ('Performance_Tally', models.SmallIntegerField(null=True)),
                ('Effort_Tally', models.SmallIntegerField(null=True)),
                ('Frustration_Tally', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
