# Generated by Django 4.0.2 on 2022-02-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_nasa_tlx_ar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nasa_tlx_ar',
            name='Effort_Tally',
        ),
        migrations.RemoveField(
            model_name='nasa_tlx_ar',
            name='Frustration_Tally',
        ),
        migrations.RemoveField(
            model_name='nasa_tlx_ar',
            name='Mental_Demand_Tally',
        ),
        migrations.RemoveField(
            model_name='nasa_tlx_ar',
            name='Performance_Tally',
        ),
        migrations.RemoveField(
            model_name='nasa_tlx_ar',
            name='Physical_Demand_Tally',
        ),
        migrations.RemoveField(
            model_name='nasa_tlx_ar',
            name='Temporal_Demand_Tally',
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Effort_or_Performance',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Effort_or_Physical_Demand',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Frustration_or_Effort',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Frustration_or_Mental_Demand',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Mental_Demand_or_Effort',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Mental_Demand_or_Physical_Demand',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Performance_or_Frustration',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Performance_or_Mental_Demand',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Performance_or_Temporal_Demand',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Physical_Demand_or_Frustration',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Physical_Demand_or_Performance',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Physical_Demand_or_Temporal_Demand',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Temporal_Demand_or_Effort',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Temporal_Demand_or_Frustration',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nasa_tlx_ar',
            name='Temporal_Demand_or_Mental_Demand',
            field=models.BooleanField(null=True),
        ),
    ]
