# Generated by Django 4.0.2 on 2022-02-24 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('my_app', '0006_sus_ar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AS_AR',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('question1', models.SmallIntegerField(null=True)),
                ('question2', models.SmallIntegerField(null=True)),
                ('question3', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
