# Generated by Django 4.0.2 on 2022-02-24 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('my_app', '0007_as_ar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AS_PDF',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('question1', models.SmallIntegerField(null=True)),
                ('question2', models.SmallIntegerField(null=True)),
                ('question3', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NASA_TLX_PDF',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Mental_Demand_Rating', models.SmallIntegerField(null=True)),
                ('Physical_Demand_Rating', models.SmallIntegerField(null=True)),
                ('Temporal_Demand_Rating', models.SmallIntegerField(null=True)),
                ('Performance_Rating', models.SmallIntegerField(null=True)),
                ('Effort_Rating', models.SmallIntegerField(null=True)),
                ('Frustration_Rating', models.SmallIntegerField(null=True)),
                ('Effort_or_Performance', models.BooleanField(null=True)),
                ('Temporal_Demand_or_Frustration', models.BooleanField(null=True)),
                ('Temporal_Demand_or_Effort', models.BooleanField(null=True)),
                ('Physical_Demand_or_Frustration', models.BooleanField(null=True)),
                ('Performance_or_Frustration', models.BooleanField(null=True)),
                ('Physical_Demand_or_Temporal_Demand', models.BooleanField(null=True)),
                ('Physical_Demand_or_Performance', models.BooleanField(null=True)),
                ('Temporal_Demand_or_Mental_Demand', models.BooleanField(null=True)),
                ('Frustration_or_Effort', models.BooleanField(null=True)),
                ('Performance_or_Mental_Demand', models.BooleanField(null=True)),
                ('Performance_or_Temporal_Demand', models.BooleanField(null=True)),
                ('Mental_Demand_or_Effort', models.BooleanField(null=True)),
                ('Mental_Demand_or_Physical_Demand', models.BooleanField(null=True)),
                ('Effort_or_Physical_Demand', models.BooleanField(null=True)),
                ('Frustration_or_Mental_Demand', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SUS_PDF',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('question1', models.SmallIntegerField(null=True)),
                ('question2', models.SmallIntegerField(null=True)),
                ('question3', models.SmallIntegerField(null=True)),
                ('question4', models.SmallIntegerField(null=True)),
                ('question5', models.SmallIntegerField(null=True)),
                ('question6', models.SmallIntegerField(null=True)),
                ('question7', models.SmallIntegerField(null=True)),
                ('question8', models.SmallIntegerField(null=True)),
                ('question9', models.SmallIntegerField(null=True)),
                ('question10', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
