# Generated by Django 4.0.2 on 2022-02-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_as_pdf_nasa_tlx_pdf_sus_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='as_ar',
            options={'verbose_name': 'answer to after-study survey for AR assembly', 'verbose_name_plural': 'answers to after-study survey for AR assembly'},
        ),
        migrations.AlterModelOptions(
            name='as_pdf',
            options={'verbose_name': 'answer to after-study survey for assembly with a PDF guide', 'verbose_name_plural': 'answers to after-study survey for assembly with a PDF guide'},
        ),
        migrations.AlterModelOptions(
            name='nasa_tlx_ar',
            options={'verbose_name': 'answer to Nasa TLX survey for AR assembly', 'verbose_name_plural': 'answers to Nasa TLX survey for AR assembly'},
        ),
        migrations.AlterModelOptions(
            name='nasa_tlx_pdf',
            options={'verbose_name': 'answer to Nasa TLX survey for assembly with a PDF guide', 'verbose_name_plural': 'answers to Nasa TLX survey for assembly with a PDF guide'},
        ),
        migrations.AlterModelOptions(
            name='sus_ar',
            options={'verbose_name': 'answer to SUS survey for AR assembly', 'verbose_name_plural': 'answers to SUS survey for AR assembly'},
        ),
        migrations.AlterModelOptions(
            name='sus_pdf',
            options={'verbose_name': 'answer to SUS survey for assembly with a PDF guide', 'verbose_name_plural': 'answers to SUS survey for assembly with a PDF guide'},
        ),
        migrations.AlterModelOptions(
            name='time_spend_ar',
            options={'verbose_name': 'time spent for assembly in AR ', 'verbose_name_plural': 'times spent for assembly in AR '},
        ),
        migrations.AlterModelOptions(
            name='time_spend_pdf',
            options={'verbose_name': 'time spent for assembly with a PDF guide ', 'verbose_name_plural': 'times spent for assembly with a PDF guide '},
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Effort_or_Performance',
            field=models.CharField(choices=[('Effort', 'Effort'), ('Performance', 'Performance'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Effort_or_Physical_Demand',
            field=models.CharField(choices=[('Effort', 'Effort'), ('Physical Demand', 'Physical Demand'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Frustration_or_Effort',
            field=models.CharField(choices=[('Effort', 'Effort'), ('Frustration', 'Frustration'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Frustration_or_Mental_Demand',
            field=models.CharField(choices=[('Mental Demand', 'Mental Demand'), ('Frustration', 'Frustration'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Mental_Demand_or_Effort',
            field=models.CharField(choices=[('Effort', 'Effort'), ('Mental Demand', 'Mental Demand'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Mental_Demand_or_Physical_Demand',
            field=models.CharField(choices=[('Mental Demand', 'Mental Demand'), ('Physical Demand', 'Physical Demand'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Performance_or_Frustration',
            field=models.CharField(choices=[('Frustration', 'Frustration'), ('Performance', 'Performance'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Performance_or_Mental_Demand',
            field=models.CharField(choices=[('Mental Demand', 'Mental Demand'), ('Performance', 'Performance'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Performance_or_Temporal_Demand',
            field=models.CharField(choices=[('Temporal Demand', 'Temporal Demand'), ('Performance', 'Performance'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Physical_Demand_or_Frustration',
            field=models.CharField(choices=[('Physical Demand', 'Physical Demand'), ('Frustration', 'Frustration'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Physical_Demand_or_Performance',
            field=models.CharField(choices=[('Physical Demand', 'Physical Demand'), ('Performance', 'Performance'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Physical_Demand_or_Temporal_Demand',
            field=models.CharField(choices=[('Physical Demand', 'Physical Demand'), ('Temporal Demand', 'Temporal Demand'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Temporal_Demand_or_Effort',
            field=models.CharField(choices=[('Temporal Demand', 'Temporal Demand'), ('Effort', 'Effort'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Temporal_Demand_or_Frustration',
            field=models.CharField(choices=[('Temporal Demand', 'Temporal Demand'), ('Frustration', 'Frustration'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_ar',
            name='Temporal_Demand_or_Mental_Demand',
            field=models.CharField(choices=[('Temporal Demand', 'Temporal Demand'), ('Mental Demand', 'Mental Demand'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Effort_or_Performance',
            field=models.CharField(choices=[('Effort', 'Effort'), ('Performance', 'Performance'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Effort_or_Physical_Demand',
            field=models.CharField(choices=[('Effort', 'Effort'), ('Physical Demand', 'Physical Demand'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Frustration_or_Effort',
            field=models.CharField(choices=[('Effort', 'Effort'), ('Frustration', 'Frustration'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Frustration_or_Mental_Demand',
            field=models.CharField(choices=[('Mental Demand', 'Mental Demand'), ('Frustration', 'Frustration'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Mental_Demand_or_Effort',
            field=models.CharField(choices=[('Effort', 'Effort'), ('Mental Demand', 'Mental Demand'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Mental_Demand_or_Physical_Demand',
            field=models.CharField(choices=[('Mental Demand', 'Mental Demand'), ('Physical Demand', 'Physical Demand'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Performance_or_Frustration',
            field=models.CharField(choices=[('Frustration', 'Frustration'), ('Performance', 'Performance'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Performance_or_Mental_Demand',
            field=models.CharField(choices=[('Mental Demand', 'Mental Demand'), ('Performance', 'Performance'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Performance_or_Temporal_Demand',
            field=models.CharField(choices=[('Temporal Demand', 'Temporal Demand'), ('Performance', 'Performance'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Physical_Demand_or_Frustration',
            field=models.CharField(choices=[('Physical Demand', 'Physical Demand'), ('Frustration', 'Frustration'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Physical_Demand_or_Performance',
            field=models.CharField(choices=[('Physical Demand', 'Physical Demand'), ('Performance', 'Performance'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Physical_Demand_or_Temporal_Demand',
            field=models.CharField(choices=[('Physical Demand', 'Physical Demand'), ('Temporal Demand', 'Temporal Demand'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Temporal_Demand_or_Effort',
            field=models.CharField(choices=[('Temporal Demand', 'Temporal Demand'), ('Effort', 'Effort'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Temporal_Demand_or_Frustration',
            field=models.CharField(choices=[('Temporal Demand', 'Temporal Demand'), ('Frustration', 'Frustration'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nasa_tlx_pdf',
            name='Temporal_Demand_or_Mental_Demand',
            field=models.CharField(choices=[('Temporal Demand', 'Temporal Demand'), ('Mental Demand', 'Mental Demand'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
    ]
