# Generated by Django 4.0 on 2022-03-04 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('my_app', '0010_assembly_alter_as_ar_question1_alter_as_ar_question2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custome_questions',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('age', models.CharField(choices=[('1', '-20 '), ('2', '20 - 30'), ('3', '30 - 40'), ('4', '40 - 50'), ('5', '50 - 60'), ('6', '+60'), (None, 'Not answered')], default=None, max_length=20, null=True)),
                ('experience', models.CharField(choices=[('1', 'This is my first experience in augmented reality'), ('2', 'I had already experimented augmented reality'), ('3', 'I regularly use augmented reality'), (None, 'Not answered')], default=None, max_length=150, null=True)),
                ('discomfort', models.CharField(choices=[('0', 'No'), ('1', 'Yes'), (None, 'Not answered')], default=None, max_length=20, null=True)),
                ('daily_use', models.CharField(choices=[('0', 'I would like it'), ('1', 'I would prefer a traditional method'), (None, 'Not answered')], default=None, max_length=50, null=True)),
                ('pause_function', models.PositiveSmallIntegerField(null=True)),
                ('speed', models.PositiveSmallIntegerField(null=True)),
                ('visibility', models.PositiveSmallIntegerField(null=True)),
                ('free_text', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Custome question',
                'verbose_name_plural': 'Custom questions',
            },
        ),
    ]
