# Generated by Django 4.0 on 2022-04-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_custome_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custome_questions_PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Custom question PDF',
                'verbose_name_plural': 'Custom questions PDF',
            },
        ),
        migrations.AlterModelOptions(
            name='custome_questions',
            options={'verbose_name': 'Custom question AR', 'verbose_name_plural': 'Custom questions AR'},
        ),
        migrations.AddField(
            model_name='custome_questions',
            name='pause_use',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='custome_questions',
            name='reverse_use',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='custome_questions',
            name='daily_use',
            field=models.CharField(choices=[('1', 'I would like it'), ('0', 'I would prefer a traditional method'), (None, 'Not answered')], default=None, max_length=50, null=True),
        ),
    ]
