# Generated by Django 4.0 on 2022-04-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('my_app', '0012_custome_questions_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custome_questions_pdf',
            name='id',
        ),
        migrations.AddField(
            model_name='custome_questions_pdf',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
    ]
