# Generated by Django 4.0 on 2022-04-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_remove_custome_questions_pdf_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custome_questions',
            name='glasses',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes'), (None, 'Not answered')], default=None, max_length=20, null=True),
        ),
    ]
